apiVersion: v1
kind: Pod
metadata:
  name: jaegertracing
spec:
  containers:
    - name: jaegertracing
      image: jaegertracing/all-in-one:1.36
      env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ':9411'
        - name: COLLECTOR_OTLP_ENABLED
          value: 'true'
      ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 16686
          protocol: TCP
        - containerPort: 4317
          protocol: TCP
        - containerPort: 4318
          protocol: TCP
        - containerPort: 14250
          protocol: TCP
        - containerPort: 14268
          protocol: TCP
        - containerPort: 14269
          protocol: TCP
        - containerPort: 9411
          protocol: TCP
